lib/poker_ex_web/router.ex
defmodule PokerExWeb.Router do
  use PokerExWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Phoenix.LiveView.Flash
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug(:fetch_session)
    plug(:accepts, ["json"])
  end

  pipeline :api_auth do
    plug(Guardian.Plug.VerifyHeader, realm: "Bearer")
    plug(Guardian.Plug.LoadResource)
  end

  pipeline :auth do
    plug PokerEx.Auth.Pipeline
  end

  pipeline :ensure_authenticated do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", PokerExWeb do
    pipe_through :browser

    get "/", HomeController, :index
    resources "/games", GameController, only: [:show]
  end

  # if Mix.env == :dev do
  #  forward "/sent_emails", Bamboo.EmailPreviewPlug
  # end
  scope "/api", PokerExWeb do
    pipe_through(:api)

    resources("/sessions", SessionController, only: [:create])
    resources("/registrations", RegistrationController, only: [:create])
    post("/auth", AuthController, :oauth_handler)
    get("/list/:player/:page", PlayerController, :list)
    post("/forgot_password", ForgotPasswordController, :forgot_password)
    post("/reset_password", ResetPasswordController, :reset_password)
  end
end

lib/poker_ex_web/controllers/home_controller.ex
defmodule PokerExWeb.HomeController do
  use PokerExWeb, :controller
  alias Phoenix.LiveView
  alias PokerExWeb.Live.Home

  def index(conn, _params) do
    LiveView.Controller.live_render(conn, Home,
      session: %{
        games: PokerEx.GameEngine.GamesServer.get_games() |> Enum.take(12)
      }
    )
  end
end

lib/poker_ex_web/live/home.ex
defmodule PokerExWeb.Live.Home do
  alias PokerEx.GameEngine.GameEvents
  alias PokerEx.GameEngine
  use Phoenix.LiveView

  def render(assigns) do
    Phoenix.View.render(PokerExWeb.HomeView, "index.html", assigns)
  end

  def mount(%{games: games} = _session, socket) do
    send(self(), {:setup, games})
    {:ok, assign(socket, games: [])}
  end

  def handle_info({:setup, games}, socket) do
    socket =
      socket
      |> assign(games: for(game <- games, do: GameEngine.get_state(game)))

    Enum.each(socket.assigns.games, &GameEvents.subscribe/1)
    {:noreply, socket}
  end

  def handle_info(
        %Phoenix.Socket.Broadcast{event: "update", payload: %GameEngine.Impl{} = game_update},
        socket
      ) do
    socket =
      socket
      |> assign(games: update_game(socket.assigns.games, game_update))

    {:noreply, socket}
  end

  defp update_game(games, update) do
    games
    |> Enum.map(fn game ->
      case game.game_id == update.game_id do
        true -> update
        false -> game
      end
    end)
  end
end

lib/poker_ex_web/views/home_view.ex
defmodule PokerExWeb.HomeView do
  use PokerExWeb, :view

  def title(%{game_id: id}) do
    id
    |> String.replace("_", " ")
    |> String.capitalize()
  end

  def status(%{phase: phase}) do
    phase
    |> Atom.to_string()
    |> String.replace("_", "-")
    |> String.capitalize()
  end
end

lib/poker_ex_web/templates/home/index.html.leex
<div class="container">
  <div class="h-center">
    <h1 class="poker-green">Poker Ex</h1>
  </div>
  <div class="card--wrapper">
    <div class="card--container">
      <%= for {game, index} <- Enum.with_index(@games) do %>
        <div class="card u-push-bottom" data-testid="game_card">
          <%= render(PokerExWeb.IconView, "index.html", suit: Enum.at(~w(heart spade diamond club), rem(index, 4))) %>
          <h2><%= title(game) %></h2>
          <div class="grid grid--2 u-push-bottom--sm">
            <div class="number--background u-center">
              <p class="caption">Players</p>
              <p class="u-push-bottom--none"><%= length(game.seating.arrangement) %></p>
            </div>
            <div class="number--background u-center">
              <p class="caption">Status</p>
              <p class="u-push-bottom--none"><%= status(game) %></p>
            </div>
          </div>
          <div class="grid u-push-bottom--sm">
            <div class="number--background u-center">
              <p class="caption">Current Pot</p>
              <p class="u-push-bottom--none"><%= game.chips.pot %></p>
            </div>
          </div>
          <a class="btn" href="<%= Routes.game_path(PokerExWeb.Endpoint, :show, game.game_id) %>">Join Game</a>
        </div>
      <% end %>
    </div>
  </div>
</div>